//! Generated glass <-> LCD mapping (single source of truth:
//! `display_map/display_map.json`, regenerated by
//! `tools/gen_display_map.py`).
include!("../../../display_map/display_map.rs");

/// Look up the LCD RAM bit (`lcd_com`, `lcd_seg`) that drives a given glass
/// segment. The default mapping is the identity; owners of real boards edit
/// `display_map/display_map.json` to match their PCB routing.
pub fn find_glass(glass_com: u8, glass_seg: u8) -> Option<&'static MapEntry> {
    DISPLAY_MAP
        .iter()
        .find(|e| e.glass_com == glass_com && e.glass_seg == glass_seg)
}
