#!/usr/bin/env python3
"""Generate display_map.json (source of truth) and a Rust table from the F-91W skin.

The emulator shell (emulator/shell.html) renders the F-91W LCD glass as SVG
elements annotated with data-com/data-seg. The real board drives the same
glass through the board-specific segment LCD controller (LCD_RAM bits).

This script extracts every glass segment from the shell and emits:

  * display_map/display_map.json  - human-readable, editable mapping of
    (lcd_com, lcd_seg) -> (glass_com, glass_seg). The "lcd_*" fields are the
    configurable part: they describe which STM32 LCD RAM bit drives each glass
    segment on a *specific* PCB routing. The defaults are an identity mapping
    (lcd_* == glass_*) which is correct for the emulator and a placeholder for
    real hardware. Board owners correct them against their schematic.

  * display_map/display_map.rs   - generated Rust table (included by the
    watch-core crate). Regenerate with:  python3 tools/gen_display_map.py
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHELL = os.path.join(ROOT, "emulator", "shell.html")
JSON_OUT = os.path.join(ROOT, "display_map", "display_map.json")
RS_OUT = os.path.join(ROOT, "display_map", "display_map.rs")

ELEMENT_RE = re.compile(r"<[^>]+>")
ATTR_RE = re.compile(
    r'(?:data-com|data-seg|id)="(?P<val>[^"]*)"'
)
GROUP_RE = re.compile(r'<g\s+id="(?P<id>[^"]*)"')


def seg_attrs(tag: str):
    """Return (com, seg, id) from a tag, regardless of attribute order."""
    attrs = {}
    for m in ATTR_RE.finditer(tag):
        val = m.group("val")
        if val.isdigit():
            if "com" not in attrs:
                attrs["com"] = val
            elif "seg" not in attrs:
                attrs["seg"] = val
        else:
            attrs.setdefault("id", val)
    return attrs


def main() -> int:
    with open(SHELL, encoding="utf-8") as fh:
        shell = fh.read()

    # unique glass segment -> list of element ids that share it
    segments = {}
    group_id = ""
    for tag in ELEMENT_RE.finditer(shell):
        text = tag.group(0)
        gm = GROUP_RE.match(text)
        if gm:
            group_id = gm.group("id")
            continue
        a = seg_attrs(text)
        if "com" in a and "seg" in a:
            key = (int(a["com"]), int(a["seg"]))
            segments.setdefault(key, []).append(a.get("id") or group_id or "unnamed")

    entries = []
    for (com, seg), ids in sorted(segments.items()):
        entries.append(
            {
                "name": "+".join(sorted(set(ids))),
                "lcd_com": com,
                "lcd_seg": seg,
                "glass_com": com,
                "glass_seg": seg,
            }
        )

    os.makedirs(os.path.dirname(JSON_OUT), exist_ok=True)
    with open(JSON_OUT, "w", encoding="utf-8") as fh:
        json.dump(entries, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    gen_rust(entries)
    print(f"wrote {len(entries)} segments -> {JSON_OUT}")
    print(f"wrote {RS_OUT}")
    return 0


def gen_rust(entries) -> None:
    lines = [
        "// Generated by tools/gen_display_map.py. Do not edit by hand.",
        "// Source of truth: display_map/display_map.json",
        "",
        "/// One glass segment of the F-91W display.",
        "#[derive(Debug, Clone, Copy)]",
        "pub struct MapEntry {",
        "    pub name: &'static str,",
        "    pub lcd_com: u8,   /* LCD RAM COM index     */",
        "    pub lcd_seg: u8,   /* LCD RAM SEG bit index */",
        "    pub glass_com: u8, /* segment element in the skin */",
        "    pub glass_seg: u8, /* segment element in the skin */",
        "}",
        "",
        "pub const DISPLAY_MAP: &[MapEntry] = &[",
    ]
    for e in entries:
        name = e["name"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            '    MapEntry { name: "%s", lcd_com: %d, lcd_seg: %d, glass_com: %d, glass_seg: %d },'
            % (name, e["lcd_com"], e["lcd_seg"], e["glass_com"], e["glass_seg"])
        )
    lines.append("];")
    lines.append("")
    with open(RS_OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
